"""initial migration

Revision ID: 5ed327e80c76
Revises: 
Create Date: 2025-01-05 15:37:57.999608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '5ed327e80c76'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_addresses_id', table_name='addresses')
    op.drop_table('addresses')
    op.drop_index('ix_other_preferences_id', table_name='other_preferences')
    op.drop_table('other_preferences')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_user_profiles_profileId', table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_table('review')
    op.drop_index('ix_education_types_id', table_name='education_types')
    op.drop_table('education_types')
    op.drop_index('ix_languages_id', table_name='languages')
    op.drop_table('languages')
    op.drop_index('ix_certification_types_id', table_name='certification_types')
    op.drop_table('certification_types')
    op.drop_index('ix_employer_profiles_employer_id', table_name='employer_profiles')
    op.drop_table('employer_profiles')
    op.drop_index('ix_personal_details_id', table_name='personal_details')
    op.drop_table('personal_details')
    op.drop_index('ix_experiences_id', table_name='experiences')
    op.drop_table('experiences')
    op.drop_index('ix_user_notification_id', table_name='user_notification')
    op.drop_table('user_notification')
    op.drop_index('ix_jobs_id', table_name='jobs')
    op.drop_index('ix_jobs_jobTitle', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_saved_jobs_id', table_name='saved_jobs')
    op.drop_index('ix_saved_jobs_jobTitle', table_name='saved_jobs')
    op.drop_table('saved_jobs')
    op.drop_index('ix_company_information_id', table_name='company_information')
    op.drop_table('company_information')
    op.drop_index('ix_job_applications_id', table_name='job_applications')
    op.drop_table('job_applications')
    op.drop_index('ix_company_id', table_name='company')
    op.drop_table('company')
    op.drop_index('ix_additional_information_id', table_name='additional_information')
    op.drop_table('additional_information')
    op.drop_index('ix_personal_employer_information_id', table_name='personal_employer_information')
    op.drop_table('personal_employer_information')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_employer_information',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employer_profile_id', sa.VARCHAR(), nullable=True),
    sa.Column('firstName', sa.VARCHAR(), nullable=True),
    sa.Column('lastName', sa.VARCHAR(), nullable=True),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('phoneNumber', sa.VARCHAR(), nullable=True),
    sa.Column('position', sa.VARCHAR(), nullable=True),
    sa.Column('socialMediaLink', sa.VARCHAR(), nullable=True),
    sa.Column('gender', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['employer_profile_id'], ['employer_profiles.employer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_personal_employer_information_id', 'personal_employer_information', ['id'], unique=False)
    op.create_table('additional_information',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employer_profile_id', sa.VARCHAR(), nullable=True),
    sa.Column('hearAboutUs', sa.VARCHAR(), nullable=True),
    sa.Column('agreedToTerms', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['employer_profile_id'], ['employer_profiles.employer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_additional_information_id', 'additional_information', ['id'], unique=False)
    op.create_table('company',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('companyName', sa.VARCHAR(), nullable=True),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.Column('landmark', sa.VARCHAR(), nullable=True),
    sa.Column('employeesCount', sa.INTEGER(), nullable=True),
    sa.Column('reviewsCount', sa.INTEGER(), nullable=True),
    sa.Column('totalReviewRating', sa.INTEGER(), nullable=True),
    sa.Column('openings', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_company_id', 'company', ['id'], unique=False)
    op.create_table('job_applications',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('phoneNumber', sa.VARCHAR(), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('jobId', sa.VARCHAR(), nullable=True),
    sa.Column('userId', sa.VARCHAR(), nullable=True),
    sa.Column('ableToCommute', sa.BOOLEAN(), nullable=True),
    sa.Column('highQualification', sa.VARCHAR(), nullable=True),
    sa.Column('experience', sa.INTEGER(), nullable=True),
    sa.Column('coverLetter', sa.VARCHAR(), nullable=True),
    sa.Column('interviewDates', sa.VARCHAR(), nullable=True),
    sa.Column('resumePath', sa.VARCHAR(), nullable=True),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.Column('company', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('appliedOn', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_applications_id', 'job_applications', ['id'], unique=False)
    op.create_table('company_information',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employer_profile_id', sa.VARCHAR(), nullable=True),
    sa.Column('companyName', sa.VARCHAR(), nullable=True),
    sa.Column('industry', sa.VARCHAR(), nullable=True),
    sa.Column('companySize', sa.VARCHAR(), nullable=True),
    sa.Column('businessType', sa.VARCHAR(), nullable=True),
    sa.Column('companyPhoneNumber', sa.VARCHAR(), nullable=True),
    sa.Column('companyWebsite', sa.VARCHAR(), nullable=True),
    sa.Column('socialMediaLink', sa.VARCHAR(), nullable=True),
    sa.Column('desc', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['employer_profile_id'], ['employer_profiles.employer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_company_information_id', 'company_information', ['id'], unique=False)
    op.create_table('saved_jobs',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('jobTitle', sa.VARCHAR(), nullable=True),
    sa.Column('company', sa.VARCHAR(), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('description', sqlite.JSON(), nullable=True),
    sa.Column('salary', sa.VARCHAR(), nullable=True),
    sa.Column('shift', sa.VARCHAR(), nullable=True),
    sa.Column('jobType', sa.VARCHAR(), nullable=True),
    sa.Column('experience', sa.VARCHAR(), nullable=True),
    sa.Column('qualifications', sqlite.JSON(), nullable=True),
    sa.Column('responsibilities', sqlite.JSON(), nullable=True),
    sa.Column('userId', sa.VARCHAR(), nullable=True),
    sa.Column('skills', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_saved_jobs_jobTitle', 'saved_jobs', ['jobTitle'], unique=False)
    op.create_index('ix_saved_jobs_id', 'saved_jobs', ['id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('jobTitle', sa.VARCHAR(), nullable=True),
    sa.Column('company', sa.VARCHAR(), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('description', sqlite.JSON(), nullable=True),
    sa.Column('salary', sa.VARCHAR(), nullable=True),
    sa.Column('shift', sa.VARCHAR(), nullable=True),
    sa.Column('jobType', sa.VARCHAR(), nullable=True),
    sa.Column('experience', sa.VARCHAR(), nullable=True),
    sa.Column('qualifications', sqlite.JSON(), nullable=True),
    sa.Column('responsibilities', sqlite.JSON(), nullable=True),
    sa.Column('employerId', sa.VARCHAR(), nullable=True),
    sa.Column('skills', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_jobTitle', 'jobs', ['jobTitle'], unique=False)
    op.create_index('ix_jobs_id', 'jobs', ['id'], unique=False)
    op.create_table('user_notification',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('notificationType', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('message', sa.VARCHAR(), nullable=True),
    sa.Column('jobId', sa.VARCHAR(), nullable=True),
    sa.Column('userId', sa.VARCHAR(), nullable=True),
    sa.Column('position', sa.VARCHAR(), nullable=True),
    sa.Column('companyName', sa.VARCHAR(), nullable=True),
    sa.Column('deleteOrResponded', sqlite.JSON(), nullable=True),
    sa.Column('createdDate', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_notification_id', 'user_notification', ['id'], unique=False)
    op.create_table('experiences',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('userProfileId', sa.VARCHAR(), nullable=True),
    sa.Column('position', sa.VARCHAR(), nullable=True),
    sa.Column('companyName', sa.VARCHAR(), nullable=True),
    sa.Column('startDate', sa.DATE(), nullable=True),
    sa.Column('endDate', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['userProfileId'], ['user_profiles.profileId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_experiences_id', 'experiences', ['id'], unique=False)
    op.create_table('personal_details',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('userProfileId', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('heading', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('phoneNumber', sa.VARCHAR(), nullable=True),
    sa.Column('dob', sa.DATE(), nullable=True),
    sa.Column('gender', sa.VARCHAR(), nullable=True),
    sa.Column('socialMediaLink', sa.VARCHAR(), nullable=True),
    sa.Column('githubLink', sa.VARCHAR(), nullable=True),
    sa.Column('country', sa.VARCHAR(), nullable=True),
    sa.Column('state', sa.VARCHAR(), nullable=True),
    sa.Column('district', sa.VARCHAR(), nullable=True),
    sa.Column('postalCode', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['userProfileId'], ['user_profiles.profileId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_personal_details_id', 'personal_details', ['id'], unique=False)
    op.create_table('employer_profiles',
    sa.Column('employer_id', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('employer_id')
    )
    op.create_index('ix_employer_profiles_employer_id', 'employer_profiles', ['employer_id'], unique=False)
    op.create_table('certification_types',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('userProfileId', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('certificateId', sa.VARCHAR(), nullable=True),
    sa.Column('mode', sa.VARCHAR(), nullable=True),
    sa.Column('institution', sa.VARCHAR(), nullable=True),
    sa.Column('startDate', sa.DATE(), nullable=True),
    sa.Column('endDate', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['userProfileId'], ['user_profiles.profileId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_certification_types_id', 'certification_types', ['id'], unique=False)
    op.create_table('languages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('userProfileId', sa.VARCHAR(), nullable=True),
    sa.Column('language', sa.VARCHAR(), nullable=True),
    sa.Column('level', sa.VARCHAR(), nullable=True),
    sa.Column('reading', sa.BOOLEAN(), nullable=True),
    sa.Column('writing', sa.BOOLEAN(), nullable=True),
    sa.Column('speaking', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['userProfileId'], ['user_profiles.profileId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_languages_id', 'languages', ['id'], unique=False)
    op.create_table('education_types',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('userProfileId', sa.VARCHAR(), nullable=True),
    sa.Column('level', sa.VARCHAR(), nullable=True),
    sa.Column('fieldOfStudy', sa.VARCHAR(), nullable=True),
    sa.Column('startedDate', sa.DATE(), nullable=True),
    sa.Column('endedDate', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['userProfileId'], ['user_profiles.profileId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_education_types_id', 'education_types', ['id'], unique=False)
    op.create_table('review',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company_id', sa.VARCHAR(), nullable=True),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('reviewText', sa.VARCHAR(), nullable=True),
    sa.Column('reviewScore', sa.INTEGER(), nullable=True),
    sa.Column('reviewedDate', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('profileId', sa.VARCHAR(), nullable=False),
    sa.Column('skills', sqlite.JSON(), nullable=True),
    sa.Column('preferredLocations', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('profileId')
    )
    op.create_index('ix_user_profiles_profileId', 'user_profiles', ['profileId'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=1)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('other_preferences',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('userProfileId', sa.VARCHAR(), nullable=True),
    sa.Column('jobType', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['userProfileId'], ['user_profiles.profileId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_other_preferences_id', 'other_preferences', ['id'], unique=False)
    op.create_table('addresses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company_info_id', sa.VARCHAR(), nullable=True),
    sa.Column('street', sa.VARCHAR(), nullable=True),
    sa.Column('city', sa.VARCHAR(), nullable=True),
    sa.Column('landmark', sa.VARCHAR(), nullable=True),
    sa.Column('state', sa.VARCHAR(), nullable=True),
    sa.Column('country', sa.VARCHAR(), nullable=True),
    sa.Column('postalCode', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['company_info_id'], ['company_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_addresses_id', 'addresses', ['id'], unique=False)
    # ### end Alembic commands ###
