"""agina regenrated migrations

Revision ID: 6da1807c5fe3
Revises: 
Create Date: 2025-01-27 07:31:07.203372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6da1807c5fe3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('companyName', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('landmark', sa.String(), nullable=True),
    sa.Column('employeesCount', sa.Integer(), nullable=True),
    sa.Column('reviewsCount', sa.Integer(), nullable=True),
    sa.Column('totalReviewRating', sa.Integer(), nullable=True),
    sa.Column('openings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=False)
    op.create_table('employer_profiles',
    sa.Column('employer_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('employer_id')
    )
    op.create_index(op.f('ix_employer_profiles_employer_id'), 'employer_profiles', ['employer_id'], unique=False)
    op.create_table('job_applications',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phoneNumber', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('jobId', sa.String(), nullable=True),
    sa.Column('userId', sa.String(), nullable=True),
    sa.Column('ableToCommute', sa.Boolean(), nullable=True),
    sa.Column('highQualification', sa.String(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('coverLetter', sa.String(), nullable=True),
    sa.Column('interviewDates', sa.String(), nullable=True),
    sa.Column('resumePath', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('appliedOn', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_applications_id'), 'job_applications', ['id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('jobTitle', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.Column('salary', sa.String(), nullable=True),
    sa.Column('shift', sa.String(), nullable=True),
    sa.Column('jobType', sa.String(), nullable=True),
    sa.Column('experience', sa.String(), nullable=True),
    sa.Column('qualifications', sa.JSON(), nullable=True),
    sa.Column('responsibilities', sa.JSON(), nullable=True),
    sa.Column('employerId', sa.String(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_jobTitle'), 'jobs', ['jobTitle'], unique=False)
    op.create_table('saved_jobs',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('jobTitle', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.Column('salary', sa.String(), nullable=True),
    sa.Column('shift', sa.String(), nullable=True),
    sa.Column('jobType', sa.String(), nullable=True),
    sa.Column('experience', sa.String(), nullable=True),
    sa.Column('qualifications', sa.JSON(), nullable=True),
    sa.Column('responsibilities', sa.JSON(), nullable=True),
    sa.Column('userId', sa.String(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_jobs_id'), 'saved_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_saved_jobs_jobTitle'), 'saved_jobs', ['jobTitle'], unique=False)
    op.create_table('temp_otp',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('email', sa.CHAR(length=36), nullable=True),
    sa.Column('otp', sa.CHAR(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temp_otp_email'), 'temp_otp', ['email'], unique=True)
    op.create_index(op.f('ix_temp_otp_id'), 'temp_otp', ['id'], unique=False)
    op.create_table('user_notification',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('notificationType', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('jobId', sa.String(), nullable=True),
    sa.Column('userId', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('companyName', sa.String(), nullable=True),
    sa.Column('deleteOrResponded', sa.JSON(), nullable=True),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_notification_id'), 'user_notification', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('additional_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_profile_id', sa.String(), nullable=True),
    sa.Column('hearAboutUs', sa.String(), nullable=True),
    sa.Column('agreedToTerms', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['employer_profile_id'], ['employer_profiles.employer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_additional_information_id'), 'additional_information', ['id'], unique=False)
    op.create_table('company_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_profile_id', sa.String(), nullable=True),
    sa.Column('companyName', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('companySize', sa.String(), nullable=True),
    sa.Column('businessType', sa.String(), nullable=True),
    sa.Column('companyPhoneNumber', sa.String(), nullable=True),
    sa.Column('companyWebsite', sa.String(), nullable=True),
    sa.Column('socialMediaLink', sa.String(), nullable=True),
    sa.Column('desc', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employer_profile_id'], ['employer_profiles.employer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_information_id'), 'company_information', ['id'], unique=False)
    op.create_table('personal_employer_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_profile_id', sa.String(), nullable=True),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phoneNumber', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('socialMediaLink', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employer_profile_id'], ['employer_profiles.employer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_employer_information_id'), 'personal_employer_information', ['id'], unique=False)
    op.create_table('review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('reviewText', sa.String(), nullable=True),
    sa.Column('reviewScore', sa.Integer(), nullable=True),
    sa.Column('reviewedDate', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('profileId', sa.String(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('preferredLocations', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('profileId')
    )
    op.create_index(op.f('ix_user_profiles_profileId'), 'user_profiles', ['profileId'], unique=False)
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_info_id', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('landmark', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('postalCode', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_info_id'], ['company_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_table('certification_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userProfileId', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('certificateId', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('startDate', sa.Date(), nullable=True),
    sa.Column('endDate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['userProfileId'], ['user_profiles.profileId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certification_types_id'), 'certification_types', ['id'], unique=False)
    op.create_table('education_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userProfileId', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('fieldOfStudy', sa.String(), nullable=True),
    sa.Column('startedDate', sa.Date(), nullable=True),
    sa.Column('endedDate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['userProfileId'], ['user_profiles.profileId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_types_id'), 'education_types', ['id'], unique=False)
    op.create_table('experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userProfileId', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('companyName', sa.String(), nullable=True),
    sa.Column('startDate', sa.Date(), nullable=True),
    sa.Column('endDate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['userProfileId'], ['user_profiles.profileId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiences_id'), 'experiences', ['id'], unique=False)
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userProfileId', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('reading', sa.Boolean(), nullable=True),
    sa.Column('writing', sa.Boolean(), nullable=True),
    sa.Column('speaking', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['userProfileId'], ['user_profiles.profileId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_languages_id'), 'languages', ['id'], unique=False)
    op.create_table('other_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userProfileId', sa.String(), nullable=True),
    sa.Column('jobType', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['userProfileId'], ['user_profiles.profileId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_other_preferences_id'), 'other_preferences', ['id'], unique=False)
    op.create_table('personal_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userProfileId', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phoneNumber', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('socialMediaLink', sa.String(), nullable=True),
    sa.Column('githubLink', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('postalCode', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['userProfileId'], ['user_profiles.profileId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_details_id'), 'personal_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personal_details_id'), table_name='personal_details')
    op.drop_table('personal_details')
    op.drop_index(op.f('ix_other_preferences_id'), table_name='other_preferences')
    op.drop_table('other_preferences')
    op.drop_index(op.f('ix_languages_id'), table_name='languages')
    op.drop_table('languages')
    op.drop_index(op.f('ix_experiences_id'), table_name='experiences')
    op.drop_table('experiences')
    op.drop_index(op.f('ix_education_types_id'), table_name='education_types')
    op.drop_table('education_types')
    op.drop_index(op.f('ix_certification_types_id'), table_name='certification_types')
    op.drop_table('certification_types')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_user_profiles_profileId'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_table('review')
    op.drop_index(op.f('ix_personal_employer_information_id'), table_name='personal_employer_information')
    op.drop_table('personal_employer_information')
    op.drop_index(op.f('ix_company_information_id'), table_name='company_information')
    op.drop_table('company_information')
    op.drop_index(op.f('ix_additional_information_id'), table_name='additional_information')
    op.drop_table('additional_information')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_notification_id'), table_name='user_notification')
    op.drop_table('user_notification')
    op.drop_index(op.f('ix_temp_otp_id'), table_name='temp_otp')
    op.drop_index(op.f('ix_temp_otp_email'), table_name='temp_otp')
    op.drop_table('temp_otp')
    op.drop_index(op.f('ix_saved_jobs_jobTitle'), table_name='saved_jobs')
    op.drop_index(op.f('ix_saved_jobs_id'), table_name='saved_jobs')
    op.drop_table('saved_jobs')
    op.drop_index(op.f('ix_jobs_jobTitle'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_job_applications_id'), table_name='job_applications')
    op.drop_table('job_applications')
    op.drop_index(op.f('ix_employer_profiles_employer_id'), table_name='employer_profiles')
    op.drop_table('employer_profiles')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
