"""added tempotp folder

Revision ID: 9249e679bfde
Revises: 86c7b24f3f92
Create Date: 2025-01-25 20:06:49.672257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9249e679bfde'
down_revision: Union[str, None] = '86c7b24f3f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_otp',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('email', sa.CHAR(length=36), nullable=True),
    sa.Column('otp', sa.CHAR(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temp_otp_email'), 'temp_otp', ['email'], unique=True)
    op.create_index(op.f('ix_temp_otp_id'), 'temp_otp', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temp_otp_id'), table_name='temp_otp')
    op.drop_index(op.f('ix_temp_otp_email'), table_name='temp_otp')
    op.drop_table('temp_otp')
    # ### end Alembic commands ###
